export const CREATE_PATTERN = "CREATE_PATTERN";
export const ENTER_WORDS = "ENTER_WORDS";
export const ENTER_DOWN_WORDS = "ENTER_DOWN_WORDS";
export const ENTER_ACROSS_WORDS = "ENTER_ACROSS_WORDS";
export const MODES = [CREATE_PATTERN, ENTER_DOWN_WORDS, ENTER_ACROSS_WORDS];
