export const CREATE_PATTERN = "CREATE_PATTERN";
export const ENTER_WORDS = "ENTER_WORDS";
export const GO_TOP_TO_BOTTOM = "GO_TOP_TO_BOTTOM";
export const GO_BOTTOM_TO_TOP = "GO_BOTTOM_TO_TOP";
export const GO_LEFT_TO_RIGHT = "GO_LEFT_TO_RIGHT";
export const GO_RIGHT_TO_LEFT = "GO_RIGHT_TO_LEFT";
export const MODES = [
  CREATE_PATTERN,
  GO_TOP_TO_BOTTOM,
  GO_BOTTOM_TO_TOP,
  GO_LEFT_TO_RIGHT,
  GO_RIGHT_TO_LEFT,
];
